version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql57_container
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: onion1!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user
      MYSQL_PASSWORD: onion1!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
