services:
  mysql-db:
    image: mysql/mysql-server:5.7
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: onion1!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user
      MYSQL_PASSWORD: onion1!
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: